#  Xcode version announcments can be found here: https://discuss.circleci.com/c/announcements/
#  Each post contains a full image manifest, including iOS runtimes, devices, CocoaPods version, etc.
#  NOTE: When updaing Xcode check the manifest for compatible chruby versions.
anchors:
  - &android-env     "cimg/android:2023.08.1-node"
  - &latest-xcode    "14.3.1"
  - &latest-ios      "16.4"
  - &min-ios         "15.5"
  - &device          "iPhone-SE-3rd-generation"
  - &invalid         ""
  - &MobileSyncExplorerReactNative
      https://github.com/forcedotcom/SalesforceMobileSDK-Templates/MobileSyncExplorerReactNative\#dev
  - &MobileSyncSwiftTemplate
      https://github.com/forcedotcom/SalesforceMobileSDK-Templates/MobileSyncExplorerSwift\#dev

version: 2.1
jobs:
  test-android:
    parameters:
      app_type: 
        type: string
        default: "native"
      template:
        type: boolean
        default: false
      sfdx:
        type: boolean
        default: false
      adv_auth:
        type: boolean
        default: false
      complex_hybrid:
        type: boolean
        default: false
    docker:
      - image: *android-env
    environment:
      GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx2024m -XX:MaxPermSize=2024m -XX:+HeapDumpOnOutOfMemoryError"'
      FASTLANE_SKIP_UPDATE_CHECK: "true"
    steps:
      - checkout
      - run: 
          name: Setup
          command: ./install.sh
          when: always
      - run: 
          name: Authorize gcloud and set config defaults
          command:  |
            echo $GCLOUD_SERVICE_KEY | base64 --decode --ignore-garbage > ${HOME}/gcloud-service-key.json
            gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
            gcloud --quiet config set project mobile-apps-firebase-test
      - run:
          name: Install SFDX
          command: |
            sudo chown -R `whoami` /usr/local/
            npm install -g sfdx-cli
            sudo chown -R `whoami` $HOME/.config/
      - run:
          name: Update Build Tools
          command: sdkmanager --install "build-tools;32.0.0"
      - when:
          condition: << parameters.template >>
          steps:
            - run:
                name: Test Android Template
                command: cd .circleci && fastlane android template:<< parameters.app_type >> sfdx:<< parameters.sfdx >>
                when: always
                no_output_timeout: 30m
      - unless:
          condition: << parameters.template >>
          steps:
            - when:
                condition: << parameters.complex_hybrid >>
                steps:
                  - run:
                      name: Test Android Complex Hybrid - Account Editor
                      command: cd .circleci && fastlane android type:hybrid_local complexHybrid:accounteditor sfdx:<< parameters.sfdx >>
                      when: always
                  - run:
                      name: Test Android Complex Hybrid - Mobile Sync Explorer
                      command: cd .circleci && fastlane android type:hybrid_local complexHybrid:mobilesyncexplorer sfdx:<< parameters.sfdx >>
                      when: always
            - unless: 
                condition: << parameters.complex_hybrid >>
                steps:
                  - run:
                      name: Test << parameters.app_type >> Android
                      command: cd .circleci && fastlane android type:<< parameters.app_type >> sfdx:<< parameters.sfdx >> adv_auth:<< parameters.adv_auth >>
                      when: always
                      no_output_timeout: 30m
      - run: 
          name: Copy test results data
          command: |
            mkdir -p firebase/results
            gsutil -m cp -r gs://test-lab-w87i9sz6q175u-kwp8ium6js0zw/UITest-<< parameters.app_type >>-${CIRCLE_BUILD_NUM} ./firebase/ || true

            count=0
            for result in $(find ./firebase/ -name 'test_result*'); do
              mv $result "./firebase/results/result${count}.xml" && (( count++ )) || true 
            done
          when: always
      - store_artifacts:
          path: firebase
      - store_test_results:
          path: firebase/results
      - store_artifacts:
          path: test_output

  test-ios:
    parameters:
      app_type: 
        type: string
        default: "native"
      template:
        type: boolean
        default: false
      adv_auth:
        type: boolean
        default: false
      complex_hybrid:
        type: boolean
        default: false
      sfdx:
        type: boolean
        default: false
      xcode:
        type: string
        default: *latest-xcode
      ios:
        type: string
        default: *latest-ios
      device:
        type: string
        default: *device
    macos:
      xcode: << parameters.xcode >>
    resource_class: macos.m1.medium.gen1
    environment:
      FASTLANE_SKIP_UPDATE_CHECK: "true"
    steps:
      - checkout
      - run: 
          name: Setup
          command: ./install.sh
          when: always
      - run:
          name: Install SFDX
          command: |
            sudo npm install -g sfdx-cli
      - when:
          condition: << parameters.template >>
          steps:
            - run:
                name: Test iOS << parameters.ios >> Template
                command: |
                  sudo chown -R $USER:$GROUP ~/.npm
                  cd .circleci
                  fastlane ios template:<< parameters.app_type >> ios:<< parameters.ios >> device:"<< parameters.device >>" sfdx:<< parameters.sfdx >>
                when: always
                no_output_timeout: 20m
      - unless:
          condition: << parameters.template >>
          steps:
            - when:
                condition: << parameters.complex_hybrid >>
                steps:
                  - run:
                      name: Test iOS << parameters.ios >> Complex Hybrid - Account Editor
                      command:  |
                          sudo chown -R $USER:$GROUP ~/.npm
                          sudo chown -R `whoami` /Users/`whoami`/Library/Preferences/
                          cd .circleci && fastlane ios type:hybrid_local ios:<< parameters.ios >> device:"<< parameters.device >>" complexHybrid:accounteditor sfdx:<< parameters.sfdx >>
                      when: always
                  - run:
                      name: Test iOS << parameters.ios >> Complex Hybrid - Mobile Sync Explorer
                      command:  |
                          sudo chown -R $USER:$GROUP ~/.npm
                          sudo chown -R `whoami` /Users/`whoami`/Library/Preferences/
                          cd .circleci && fastlane ios type:hybrid_local ios:<< parameters.ios >> device:"<< parameters.device >>" complexHybrid:mobilesyncexplorer sfdx:<< parameters.sfdx >>
                      when: always
            - unless: 
                condition: << parameters.complex_hybrid >>
                steps:
                  - run:
                      name: Test << parameters.app_type >> iOS << parameters.ios >>
                      command:  |
                          sudo chown -R $USER:$GROUP ~/.npm
                          sudo chown -R `whoami` /Users/`whoami`/Library/Preferences/
                          cd .circleci && fastlane ios type:<< parameters.app_type >> ios:<< parameters.ios >> device:"<< parameters.device >>" sfdx:<< parameters.sfdx >> adv_auth:<< parameters.adv_auth >>
                      when: always
                      no_output_timeout: 20m
      - store_artifacts:
          path: test_output

  test-carthage:
    parameters:
      sfdx:
        type: boolean
        default: false
      xcode:
        type: string
        default: *latest-xcode
      ios:
        type: string
        default: *latest-ios
      device:
        type: string
        default: *device
    macos:
      xcode: << parameters.xcode >>
    resource_class: macos.x86.medium.gen2
    environment:
      GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx4096m -XX:MaxPermSize=4096m -XX:+HeapDumpOnOutOfMemoryError"'
      FASTLANE_SKIP_UPDATE_CHECK: "true"
    steps:
      - checkout
      - run: 
          name: Setup
          command: ./install.sh
          when: always
      - run:
          name: Install Carthage
          command: brew upgrade carthage
      - run:
          name: Test Carthage
          command: cd .circleci && fastlane test_carthage ios:<< parameters.ios >> device:"<< parameters.device >>"
          when: always
      - store_artifacts:
          path: test_output
      - store_test_results:
          path: test_output

#  Potential parameters that can come from the project GUI Triggers
parameters:
  xcode:
    type: string
    default: *invalid
  ios:
    type: string
    default: *invalid
  device:
    type: string
    default: *device

workflows:
  version: 2

  pr:
    when: 
      and:
        - equal: [ "webhook", << pipeline.trigger_source >> ]
    jobs:
      - test-android:
          name: Android << matrix.app_type >>
          context: Mobile SDK UI Tests
          matrix:
            parameters: 
              app_type: ["native", "native_kotlin", "hybrid_local", "hybrid_remote", "react_native"]
          filters:
            branches:
              only:
                - /pull.*/
      - test-ios:
          name: iOS << matrix.ios >> << matrix.app_type >> 
          context: Mobile SDK UI Tests
          matrix:
            parameters: 
              app_type: ["native", "native_swift", "hybrid_local", "hybrid_remote", "react_native"]
              ios: [*min-ios, *latest-ios]
          filters:
            branches:
              only:
                - /pull.*/
              
  # Scheduled Trigger on Saturday Afternoon
  build-all-apps:
    when:
      and:
        - not: << pipeline.parameters.xcode >>
        - not:  
            equal: [ "webhook", << pipeline.trigger_source >> ]
    jobs:
      - test-android:
          name: Android << matrix.app_type >> SFDX-<< matrix.sfdx >>
          context: Mobile SDK UI Tests
          matrix:
            parameters: 
              app_type: ["native", "native_kotlin", "hybrid_local", "hybrid_remote", "react_native"]
              sfdx: [true, false]
      - test-android:
          name: Android MobileSyncExplorerReactNative SFDX-<< matrix.sfdx >>
          context: Mobile SDK UI Tests
          matrix:
            parameters: 
              app_type: [*MobileSyncExplorerReactNative]
              template: [true]
              sfdx: [true, false]
      - test-android:
          name: Android Advanced Auth
          context: Mobile SDK UI Tests
          adv_auth: true
      - test-android:
          name: Android Complex Hybrid
          context: Mobile SDK UI Tests
          complex_hybrid: true
      - test-ios:
          name: iOS << matrix.ios >> << matrix.app_type >> SFDX-<< matrix.sfdx >>
          context: Mobile SDK UI Tests
          matrix:
            parameters: 
              app_type: ["native", "native_swift", "hybrid_local", "hybrid_remote", "react_native"]
              ios: [*min-ios, *latest-ios]
              sfdx: [true, false]
      - test-ios:
          name: iOS << matrix.ios >> << matrix.app_type >> Template
          context: Mobile SDK UI Tests
          matrix: 
            parameters: 
              app_type: [*MobileSyncExplorerReactNative, *MobileSyncSwiftTemplate]
              ios: [*min-ios, *latest-ios]
              template: [true]
      - test-ios:
          name: iOS << matrix.ios >> Advanced Auth
          context: Mobile SDK UI Tests
          matrix:
            parameters:  
              adv_auth: [true]
              ios: [*min-ios, *latest-ios]
      - test-ios:
          name: iOS << matrix.ios >> Complex Hybrid
          context: Mobile SDK UI Tests
          matrix:
            parameters:  
              complex_hybrid: [true]
              ios: [*min-ios, *latest-ios]
      - test-carthage:
          name: iOS << matrix.ios >> Carthage
          context: Mobile SDK UI Tests
          matrix:
            parameters: 
              ios: [*min-ios, *latest-ios]

  # Scheduled Trigger (when beta exists) on Saturday Afternoon
  build-all-apps-ios-beta:
    when:
      and:
        - << pipeline.parameters.xcode >>
        - << pipeline.parameters.ios >>
        - not:  
            equal: [ "webhook", << pipeline.trigger_source >> ]
    jobs:
      - test-ios:
          name: iOS << pipeline.parameters.ios >> << matrix.app_type >> SFDX-<< matrix.sfdx >>
          context: Mobile SDK UI Tests
          matrix:
            parameters: 
              app_type: ["native", "native_swift", "hybrid_local", "hybrid_remote", "react_native"]
              xcode: [<< pipeline.parameters.xcode >>]
              ios: [<< pipeline.parameters.ios >>]
              device: [<< pipeline.parameters.device >>]
              sfdx: [true, false]
      - test-ios:
          name: iOS << pipeline.parameters.ios >> << matrix.app_type >> Template
          context: Mobile SDK UI Tests
          matrix: 
            parameters: 
              app_type: [*MobileSyncExplorerReactNative, *MobileSyncSwiftTemplate]
              xcode: [<< pipeline.parameters.xcode >>]
              ios: [<< pipeline.parameters.ios >>]
              device: [<< pipeline.parameters.device >>]
              template: [true]
      - test-ios:
          name: iOS << pipeline.parameters.ios >> Advanced Auth
          context: Mobile SDK UI Tests
          matrix:
            parameters:  
              adv_auth: [true]
              xcode: [<< pipeline.parameters.xcode >>]
              ios: [<< pipeline.parameters.ios >>]
              device: [<< pipeline.parameters.device >>]
      - test-ios:
          name: iOS << pipeline.parameters.ios >> Complex Hybrid
          context: Mobile SDK UI Tests
          matrix:
            parameters:  
              complex_hybrid: [true]
              xcode: [<< pipeline.parameters.xcode >>]
              ios: [<< pipeline.parameters.ios >>]
              device: [<< pipeline.parameters.device >>]
      - test-carthage:
          name: iOS << pipeline.parameters.ios >> Carthage
          context: Mobile SDK UI Tests
          matrix:
            parameters: 
              xcode: [<< pipeline.parameters.xcode >>]
              ios: [<< pipeline.parameters.ios >>]
              device: [<< pipeline.parameters.device >>]