aliases:
  - &upgrade-git
    name: Update Git
    command:  |
      git --version
      sudo apt-get update
      sudo apt-get install \
        build-essential flex bison \
        libreadline6-dev zlib1g-dev \
        libssl-dev \
        libcurl4-gnutls-dev \
        libexpat1-dev \
        tcl tk \
        tcl-dev gettext \
        asciidoc \
        docbook2x

      wget https://www.kernel.org/pub/software/scm/git/git-2.13.0.tar.gz
      tar -xvzf git-2.13.0.tar.gz
      cd git-2.13.0
      sudo ./configure
      sudo make && sudo make install

  - &setup
    name: Setup
    command: ./install.sh
    when: always

  - &install-ant
    name: Install Ant
    command: brew install ant

  - &gcloud-auth
    name: Authorize gcloud and set config defaults
    command:  |
        echo $GCLOUD_SERVICE_KEY | base64 --decode --ignore-garbage > ${HOME}/gcloud-service-key.json
        gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
        gcloud --quiet config set project mobile-apps-firebase-test
        
  - &get-firebase-results
    name: Copy test results data
    command: |
        mkdir -p firebase/results
        gsutil -m cp -r -U "`gsutil ls gs://test-lab-w87i9sz6q175u-kwp8ium6js0zw/UITest-Local-${CIRCLE_BUILD_NUM} | tail -1`*" ./firebase/
        mv firebase/test_result_1.xml firebase/results
    when: always

linux: &linux
  working_directory: ~/SalesforceMobileSDK-UITest
  docker:
    - image: circleci/android:api-28-node
  environment:
    - TERM: "dumb"
    - ADB_INSTALL_TIMEOUT: 15
    - GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx2048m -XX:+HeapDumpOnOutOfMemoryError"'

mac: &mac
  working_directory: ~/SalesforceMobileSDK-UITest
  macos:
    xcode: "10.2.1"
  shell: /bin/bash --login -eo pipefail

mac_android: &mac_android
  working_directory: ~/SalesforceMobileSDK-UITest
  macos:
    xcode: "10.2.1"
  shell: /bin/bash --login -eo pipefail
  environment:
    - TERM: dumb
    - ADB_INSTALL_TIMEOUT: 15
    - GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx2048m -XX:+HeapDumpOnOutOfMemoryError"'

version: 2
jobs:
  test-android:
    <<: *mac_android
    steps:
      - checkout
      - run:
          name: Setup environment variables
          command: |
            echo 'export PATH="$PATH:/usr/local/opt/node@8/bin:${HOME}/.yarn/bin:${HOME}/${CIRCLE_PROJECT_REPONAME}/node_modules/.bin:/usr/local/share/android-sdk/tools/bin"' >> $BASH_ENV
            echo 'export ANDROID_HOME="/usr/local/share/android-sdk"' >> $BASH_ENV
            echo 'export ANDROID_SDK_HOME="/usr/local/share/android-sdk"' >> $BASH_ENV
            echo 'export ANDROID_SDK_ROOT="/usr/local/share/android-sdk"' >> $BASH_ENV
            echo 'export QEMU_AUDIO_DRV=none' >> $BASH_ENV
            echo 'export JAVA_HOME=/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home' >> $BASH_ENV
      - run:
          name: Install Android sdk
          command: |
            HOMEBREW_NO_AUTO_UPDATE=1 brew tap homebrew/cask
            HOMEBREW_NO_AUTO_UPDATE=1 brew cask install android-sdk
            HOMEBREW_NO_AUTO_UPDATE=1 brew cask install adoptopenjdk/openjdk/adoptopenjdk8
      - run:
          name: Install emulator dependencies
          command: (yes | sdkmanager "platform-tools" "platforms;android-26" "extras;intel;Hardware_Accelerated_Execution_Manager" "build-tools;26.0.0" "system-images;android-26;google_apis;x86" "emulator" --verbose) || true
          #command: (yes | sdkmanager "platform-tools" "platforms;android-${API_VERSION}" "extras;intel;Hardware_Accelerated_Execution_Manager" "build-tools;${API_VERSION}.0.0" "system-images;android-${API_VERSION};google_apis;x86" "emulator" --verbose) || true
      - run: 
          name: Create AVD
          command: avdmanager create avd -n Pixel_2_API_26 -k "system-images;android-26;google_apis;x86" -g google_apis -d "Nexus 5"
          #command: avdmanager create avd -n "${DEVICE}_API_${API_VERSION}" -k "system-images;android-${API_VERSION};google_apis;x86" -g google_apis -d "Nexus 5"
      - run:
          name: Run emulator in background
          command: /usr/local/share/android-sdk/tools/emulator @Pixel_2_API_26 -skin 1080x2066 -memory 2048 -dns-server 8.8.8.8,8.8.4.4 -noaudio 
          #command: /usr/local/share/android-sdk/tools/emulator "@${DEVICE}_API_${API_VERSION}" -skin 1080x2066 -memory 2048 -noaudio
          background: true
      - run:
          name: Download Android Dependencies
          command: |
            cd Android
            ./gradlew androidDependencies
      - run: *setup
      - run:
          name: Run Java Tests
          command: cd .circleci && fastlane android type:native
          when: always
          no_output_timeout: 900
      - store_artifacts:
          path: Android/app/build/reports/androidTests/connected/*
          destination: native_Java
      - store_test_results:
          path: Android/app/build/reports/androidTests/connected/com.salesforce.mobilesdk.mobilesdkuitest.Login.html
      - run:
          name: Run Kotlin Tests
          command: cd .circleci && fastlane android type:native_kotlin
          when: always
          no_output_timeout: 900
      - store_artifacts:
          path: Android/app/build/reports/androidTests/connected/*
          destination: native_kotlin
      - store_test_results:
          path: Android/app/build/reports/androidTests/connected/com.salesforce.mobilesdk.mobilesdkuitest.Login.html
      - run:
          name: Run Hybird Local Tests
          command: cd .circleci && fastlane android type:hybrid_local
          when: always
          no_output_timeout: 900
      - store_artifacts:
          path: Android/app/build/reports/androidTests/connected/*
          destination: hybrid_local
      - store_test_results:
          path: Android/app/build/reports/androidTests/connected/com.salesforce.mobilesdk.mobilesdkuitest.Login.html
      - run:
          name: Run Hybrid Remote Tests
          command: cd .circleci && fastlane android type:hybrid_remote
          when: always
          no_output_timeout: 900
      - store_artifacts:
          path: Android/app/build/reports/androidTests/connected/*
          destination: hybrid_remote
      - store_test_results:
          path: Android/app/build/reports/androidTests/connected/com.salesforce.mobilesdk.mobilesdkuitest.Login.html

  test-ios:
      <<: *mac
      steps:
        - checkout
        - run: *setup
        - run: *install-ant
        - run:
            name: Test Native Objective-C App
            command: cd .circleci && fastlane ios type:native
            when: always
            no_output_timeout: 900
        - store_artifacts:
            path: test_output/report.html
            destination: Native_Objective_C
        - store_artifacts:
            path: /home/circleci/.fastlane/latest_crash.json
            destination: Native_Objective_C
        - store_test_results:
            path: test_output/report.junit
        - run:
            name: Test Native Swift App
            command: xcrun swift -version && cd .circleci && fastlane ios type:native_swift
            when: always
            no_output_timeout: 900
        - store_artifacts:
            path: test_output/report.html
            destination: Native_Swift
        - store_artifacts:
            path: /home/circleci/.fastlane/latest_crash.json
            destination: Native_Swift
        - store_test_results:
            path: test_output/report.junit
        - run:
            name: Test Hybrid Local App
            command: cd .circleci && fastlane ios type:hybrid_local
            when: always
            no_output_timeout: 900
        - store_artifacts:
            path: test_output/report.html
            destination: Hybrid_Local
        - store_artifacts:
            path: /home/circleci/.fastlane/latest_crash.json
            destination: Hybrid_Local
        - store_test_results:
            path: test_output/report.junit
        - run:
            name: Test Hyrbid Remote App
            command: cd .circleci && fastlane ios type:hybrid_remote
            when: always
            no_output_timeout: 900
        - store_artifacts:
            path: test_output/report.html
            destination: Hybrid_Remote
        - store_artifacts:
            path: /home/circleci/.fastlane/latest_crash.json
            destination: Hybrid_Remote
        - store_test_results:
            path: test_output/report.junit


workflows:
  version: 2
  pr-build-all-apps:
    jobs:
      - test-android
      #    context: android-api-28
      #- test-android
      #    context: android-api-25
      #- test-android
      #    context: android-api-23
      #- test-android
      #    context: android-api-21
      #- test-ios:
      #    context: ios-max-version
      #- test-ios:
      #    context: ios-min-version

  # Cron are on a timezone 8 hours ahead of PST
  # Build everything on Saturday Afternoon
  weekly-build-all-apps:
    triggers:
      - schedule:
          cron: "30 19 * * 6"
          filters:
            branches:
              only:
                - master
    jobs:
      - test-android
      - test-ios