aliases:
  - &setup
    name: Setup
    command: ./install.sh
    when: always

  - &install-ant
    name: Install Ant
    command: brew install ant

linux: &linux
  working_directory: ~/SalesforceMobileSDK-UITest
  docker:
    - image: circleci/android:api-28-node
  environment:
    - TERM: "dumb"
    - ADB_INSTALL_TIMEOUT: 15
    - GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx2048m -XX:+HeapDumpOnOutOfMemoryError"'

mac: &mac
  working_directory: ~/SalesforceMobileSDK-UITest
  macos:
    xcode: "10.2.1"
  shell: /bin/bash --login -eo pipefail

mac_android: &mac_android
  working_directory: ~/SalesforceMobileSDK-UITest
  macos:
    xcode: "10.2.1"
  shell: /bin/bash --login -eo pipefail
  environment:
    TERM: dumb
    JVM_OPTS: -Xmx3200m

version: 2.1
jobs:
  test-android:
    <<: *mac_android
    parameters:
      API_LEVEL: 
        type: integer
        default: 28
    steps:
      - checkout
      - run:
          name: Setup environment variables
          command: |
            echo 'export PATH="$PATH:/usr/local/opt/node@8/bin:${HOME}/.yarn/bin:${HOME}/${CIRCLE_PROJECT_REPONAME}/node_modules/.bin:/usr/local/share/android-sdk/tools/bin"' >> $BASH_ENV
            echo 'export ANDROID_HOME="/usr/local/share/android-sdk"' >> $BASH_ENV
            echo 'export ANDROID_SDK_HOME="/usr/local/share/android-sdk"' >> $BASH_ENV
            echo 'export ANDROID_SDK_ROOT="/usr/local/share/android-sdk"' >> $BASH_ENV
            echo 'export QEMU_AUDIO_DRV=none' >> $BASH_ENV
            echo 'export JAVA_HOME=/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home' >> $BASH_ENV
      - run:
          name: Install Android sdk
          command: |
            HOMEBREW_NO_AUTO_UPDATE=1 brew tap homebrew/cask
            HOMEBREW_NO_AUTO_UPDATE=1 brew cask install android-sdk
            HOMEBREW_NO_AUTO_UPDATE=1 brew cask install adoptopenjdk/openjdk/adoptopenjdk8
      - run:
          name: Install Android API << parameters.API_LEVEL >> emulator dependencies
          command: (yes | sdkmanager "platform-tools" "platforms;android-<< parameters.API_LEVEL >>" "extras;intel;Hardware_Accelerated_Execution_Manager" "build-tools;<< parameters.API_LEVEL >>.0.0" "system-images;android-<< parameters.API_LEVEL >>;google_apis;x86" "emulator" --verbose) || true
      - run: 
          name: Create AVD
          command: avdmanager create avd -n AVD -k "system-images;android-<< parameters.API_LEVEL >>;google_apis;x86"
      - run: 
          name: Restart ADB to fix AVD Network Connection
          command: |
            $ANDROID_HOME/platform-tools/adb kill-server
            $ANDROID_HOME/platform-tools/adb start-server
      - run:
          name: Run emulator in background
          command: /usr/local/share/android-sdk/emulator/emulator AVD >> -memory 2048 -noaudio 
          background: true
      - run:
          name: Download Android Dependencies
          command: |
            cd Android
            ./gradlew androidDependencies
      - run: *setup
      - run:
          name: Run Java Tests
          command: cd .circleci && fastlane android type:native
          when: always
          no_output_timeout: 900
      - store_artifacts:
          path: Android/app/build/reports/androidTests/connected/*
          destination: native_Java
      - store_test_results:
          path: Android/app/build/reports/androidTests/connected/com.salesforce.mobilesdk.mobilesdkuitest.Login.html
      - run:
          name: Run Kotlin Tests
          command: cd .circleci && fastlane android type:native_kotlin
          when: always
          no_output_timeout: 900
      - store_artifacts:
          path: Android/app/build/reports/androidTests/connected/*
          destination: native_kotlin
      - store_test_results:
          path: Android/app/build/reports/androidTests/connected/com.salesforce.mobilesdk.mobilesdkuitest.Login.html
      - run:
          name: Run Hybird Local Tests
          command: cd .circleci && fastlane android type:hybrid_local
          when: always
          no_output_timeout: 900
      - store_artifacts:
          path: Android/app/build/reports/androidTests/connected/*
          destination: hybrid_local
      - store_test_results:
          path: Android/app/build/reports/androidTests/connected/com.salesforce.mobilesdk.mobilesdkuitest.Login.html
      - run:
          name: Run Hybrid Remote Tests
          command: cd .circleci && fastlane android type:hybrid_remote
          when: always
          no_output_timeout: 900
      - store_artifacts:
          path: Android/app/build/reports/androidTests/connected/*
          destination: hybrid_remote
      - store_test_results:
          path: Android/app/build/reports/androidTests/connected/com.salesforce.mobilesdk.mobilesdkuitest.Login.html

  test-ios:
      <<: *mac
      parameters:
        ios_version: 
            type: string
        device:
            type: string
      steps:
        - checkout
        - run: *setup
        - run: *install-ant
        - run:
            name: Test Native Objective-C App
            command: cd .circleci && fastlane ios type:native device:<< parameters.device >> ios:<< parameters.ios_version >>
            when: always
            no_output_timeout: 900
        - store_artifacts:
            path: test_output/report.html
            destination: Native_Objective_C
        - store_artifacts:
            path: /home/circleci/.fastlane/latest_crash.json
            destination: Native_Objective_C
        - store_test_results:
            path: test_output/report.junit
        - run:
            name: Test Native Swift App
            command: xcrun swift -version && cd .circleci && fastlane ios type:native_swift device:<< parameters.device >> ios:<< parameters.ios_version >>
            when: always
            no_output_timeout: 900
        - store_artifacts:
            path: test_output/report.html
            destination: Native_Swift
        - store_artifacts:
            path: /home/circleci/.fastlane/latest_crash.json
            destination: Native_Swift
        - store_test_results:
            path: test_output/report.junit
        - run:
            name: Test Hybrid Local App
            command: cd .circleci && fastlane ios type:hybrid_local device:<< parameters.device >> ios:<< parameters.ios_version >>
            when: always
            no_output_timeout: 900
        - store_artifacts:
            path: test_output/report.html
            destination: Hybrid_Local
        - store_artifacts:
            path: /home/circleci/.fastlane/latest_crash.json
            destination: Hybrid_Local
        - store_test_results:
            path: test_output/report.junit
        - run:
            name: Test Hyrbid Remote App
            command: cd .circleci && fastlane ios type:hybrid_remote device:<< parameters.device >> ios:<< parameters.ios_version >>
            when: always
            no_output_timeout: 900
        - store_artifacts:
            path: test_output/report.html
            destination: Hybrid_Remote
        - store_artifacts:
            path: /home/circleci/.fastlane/latest_crash.json
            destination: Hybrid_Remote
        - store_test_results:
            path: test_output/report.junit


workflows:
  version: 2
  pr-build-all-apps:
    jobs:
      - test-android
      - test-ios:
          device: "iPhoneXR"
          ios_version: "12.2"

  # Cron are on a timezone 8 hours ahead of PST
  # Build everything on Saturday Afternoon
  weekly-build-all-apps:
    triggers:
      - schedule:
          cron: "30 19 * * 6"
          filters:
            branches:
              only:
                - master
    jobs:
      - test-android:
          API_LEVEL: 23
      - test-android:
          API_LEVEL: 26
      - test-android:
          API_LEVEL: 28
      - test-ios:
          device: "iPhoneXR"
          ios_version: "12.2"
      - test-ios:
          device: "iPhoneX"
          ios_version: "11.4"