on:
  workflow_call:
    inputs:
      app_type:
        required: true
        type: string
      ios:
        default: '18.1'
        required: false
        type: string
      xcode: 
        default: 16.1_beta_2
        required: false
        type: string

jobs:
  test-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4.1.0
      - name: Set Xcode Version
        run: sudo xcode-select -s /Applications/Xcode_${{ inputs.xcode }}.app/Contents/Developer
      - name: Setup
        run: ./install.sh
      - name: Install SF CLI 
        if: ${{ inputs.app_type == 'hybrid_local' }}
        run: npm install -g @salesforce/cli
      - name: Test ${{ inputs.app_type }} iOS
        env:
          CI_USER_PASSWORD: ${{ secrets.CI_USER_PASSWORD }}
        run: cd .github && fastlane ios type:${{ inputs.app_type }} ios:${{ inputs.ios }}