name: Pull Request Workflow

on: [pull_request]

# use include to add sfdx to specific app types

jobs:
  test-android:
    # Permissions requried for GCloud Auth
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    container:
        image: fabernovel/android:api-34-gcloud-snapshot
    strategy:
      fail-fast: false
      matrix:
        app_type: [native, hybrid_local]
    steps:
    - uses: actions/checkout@v4.1.0
    - uses: actions/setup-node@v4
      with:
        node-version: '22'
    - name: Setup
      run: ./install.sh
    # - uses: 'google-github-actions/auth@v2'
    #   with:
    #     project_id: "${{ secrets.PROJECT_ID }}"
    #     workload_identity_provider: "${{ secrets.WORKLOAD_IDENTITY_POOL_ID }}"
    - uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCLOUD_SERVICE_KEY }}'
    - name: Install SF CLI 
      if: ${{ matrix.app_type == 'hybrid_local' }}
      run: npm install -g @salesforce/cli
    - name: Test ${{ matrix.app_type }} Android
      run: cd .github && fastlane android type:${{ matrix.app_type }}
    - name: Copy test results data
      run: |
        mkdir -p firebase/results
        gsutil -m cp -r gs://test-lab-w87i9sz6q175u-kwp8ium6js0zw/UITest-<< parameters.app_type >>-${{ github.run_id }} ./firebase/ || true

        count=0
        for result in $(find ./firebase/ -name 'test_result*'); do
            mv $result "./firebase/results/result${count}.xml" && (( count++ )) || true 
        done
      if: always()
    - uses: actions/upload-artifact@v4.1.0
      with:
        path: |
          firebase
          firebase/results
          test_output
    
    