name: Pull Request

on:
  # Dangerious without Member Check setup!
  pull_request_target:
    # branches: [master]

jobs:
  permission-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check Write Permission
        uses: octokit/request-action@v2.x
        id: check_permissions
        with:
          route: GET /repos/${{ github.repository }}/collaborators/${{ github.triggering_actor }}/permission
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Debug Permission Response
        run: |
          echo "Permission raw response: ${{ steps.check_permissions.outputs.data }}"
      - name: Validate Write Permission
        run: |
          permission=$(echo "${{ fromJson(steps.check_permissions.outputs.data).permission }}")
          echo "User ${{ github.triggering_actor }} has permission: $permission"
          if [[ "$permission" != "write" && "$permission" != "admin" ]]; then
            echo "User ${{ github.triggering_actor }} does not have sufficient permission (write or admin) to proceed. Someone from the team needs to rerun this workflow AFTER it has been deemed safe."
            exit 1
          fi

  # ios-pr:
  #   needs: [permission-check]
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       app_type: [native, hybrid_local, react_native] 
  #   uses: ./.github/workflows/ios-reusable-workflow.yaml
  #   with:
  #     app_type: ${{ matrix.app_type }}
  #     is_pr: true
  #   secrets: inherit

  # android-pr:
  #   needs: [permission-check]
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       app_type: [native, hybrid_local, react_native]
  #   uses: ./.github/workflows/android-reusable-workflow.yaml
  #   with:
  #     app_type: ${{ matrix.app_type }}
  #     is_pr: true
  #   secrets: inherit

  android-build-all:
    needs: [permission-check]
    strategy:
      fail-fast: false
      matrix:
        app_type:  [native, native_kotlin, hybrid_local, hybrid_remote, react_native, MobileSyncExplorerReactNative, AndroidNativeLoginTemplate]
        include:
            - app_type: native
              sfdx: false
            - app_type: native
              sfdx: true
            - app_type: hybrid_local
              sfdx: false
            - app_type: hybrid_local
              sfdx: true
            - app_type: react_native
              sfdx: false
            - app_type: react_native
              sfdx: true
            - app_type: MobileSyncExplorerReactNative
              template: true
            - app_type: AndroidNativeLoginTemplate
              template: true
            - adv_auth: true
              app_type: native
            - complex_hybrid: true
              app_type: hybrid_local
    uses: ./.github/workflows/android-reusable-workflow.yaml
    with:
      app_type: ${{ matrix.app_type }}
      template: ${{ matrix.template || false }}
      sfdx: ${{ matrix.sfdx || false }}
      adv_auth: ${{ matrix.adv_auth || false }}
      complex_hybrid: ${{ matrix.complex_hybrid || false }}
    secrets: inherit
    
  ios-build-all:
    needs: [permission-check]
    if: success() || failure()
    strategy:
      fail-fast: false
      matrix:
        app_type:  [native, native_kotlin, hybrid_local, hybrid_remote, react_native, MobileSyncExplorerReactNative, MobileSyncExplorerSwift, iOSNativeLoginTemplate]
        ios: ["18.2", "17.4"]
        include:
            - ios: "18.2"
              xcode: "16.2"
            - ios: "17.5"
              xcode: "15.4"
            - app_type: native
              sfdx: false
            - app_type: native
              sfdx: true
            - app_type: hybrid_local
              sfdx: false
            - app_type: hybrid_local
              sfdx: true
            - app_type: react_native
              sfdx: false
            - app_type: react_native
              sfdx: true
            - app_type: MobileSyncExplorerReactNative
              template: true
            - app_type: MobileSyncExplorerSwift
              template: true
            - app_type: iOSNativeLoginTemplate
              template: true
            - adv_auth: true
              app_type: native
            - complex_hybrid: true
              app_type: hybrid_local
    uses: ./.github/workflows/ios-reusable-workflow.yaml
    with:
      app_type: ${{ matrix.app_type }}
      ios: ${{ matrix.ios }}
      xcode: ${{ matrix.xcode }}
      template: ${{ matrix.template || false }}
      sfdx: ${{ matrix.sfdx || false }}
      adv_auth: ${{ matrix.adv_auth || false }}
      complex_hybrid: ${{ matrix.complex_hybrid || false }}
    secrets: inherit
            